"""init

Revision ID: 05dbc23df722
Revises: 
Create Date: 2025-09-23 16:58:12.345798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05dbc23df722'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modulo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('carga_horaria', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('re', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo_acesso', sa.Enum('colaborador', 'gestor', name='tipo_acesso_enum'), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuario_re'), ['re'], unique=True)

    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('notificacoes_email', sa.Boolean(), nullable=True),
    sa.Column('notificacoes_push', sa.Boolean(), nullable=True),
    sa.Column('tema', sa.String(length=20), nullable=True),
    sa.Column('idioma', sa.String(length=10), nullable=True),
    sa.Column('privacidade_perfil', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['colaborador_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracoes_colaborador_id'), ['colaborador_id'], unique=False)

    op.create_table('equipe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('gestor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gestor_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercicio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('multipla_escolha', 'dissertativo', 'pratico', name='exercicio_tipo_enum'), nullable=True),
    sa.Column('resposta_correta', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercicio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercicio_modulo_id'), ['modulo_id'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gestor_id', sa.Integer(), nullable=True),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('data_feedback', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gestor_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_colaborador_id'), ['colaborador_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_gestor_id'), ['gestor_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('password_reset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('data_expiracao', sa.DateTime(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('password_reset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('progresso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('nao_iniciado', 'em_andamento', 'concluido', name='progresso_status_enum'), nullable=False),
    sa.Column('nota_final', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'modulo_id', name='uix_progresso_usuario_modulo')
    )
    with op.batch_alter_table('progresso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progresso_modulo_id'), ['modulo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progresso_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('relatorio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gestor_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gestor_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relatorio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relatorio_gestor_id'), ['gestor_id'], unique=False)

    op.create_table('equipe_colaborador',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipe_colaborador')
    with op.batch_alter_table('relatorio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relatorio_gestor_id'))

    op.drop_table('relatorio')
    with op.batch_alter_table('progresso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progresso_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_progresso_modulo_id'))

    op.drop_table('progresso')
    with op.batch_alter_table('password_reset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_usuario_id'))

    op.drop_table('password_reset')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_usuario_id'))

    op.drop_table('notification')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_gestor_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_colaborador_id'))

    op.drop_table('feedback')
    with op.batch_alter_table('exercicio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercicio_modulo_id'))

    op.drop_table('exercicio')
    op.drop_table('equipe')
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracoes_colaborador_id'))

    op.drop_table('configuracoes')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_re'))
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    op.drop_table('modulo')
    # ### end Alembic commands ###
