"""Adiciona coluna colaborador_id na tabela relatorio

Revision ID: 3256149f1ca8
Revises: 0f8d18e8c5df
Create Date: 2025-11-10 13:43:29.144460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3256149f1ca8'
down_revision = '0f8d18e8c5df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_notificacao')
    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('online', 'offline'),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'offline'"))

    with op.batch_alter_table('relatorio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colaborador_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_relatorio_colaborador_id'), ['colaborador_id'], unique=False)
        batch_op.create_foreign_key(None, 'usuario', ['colaborador_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_relatorio_colaborador_id'))
        batch_op.drop_column('colaborador_id')

    with op.batch_alter_table('colaboradores', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('online', 'offline'),
               existing_nullable=True,
               existing_server_default=sa.text("'offline'"))

    op.create_table('usuario_notificacao',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', mysql.ENUM('email', 'push'), nullable=False),
    sa.Column('ativo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('usuario_notificacao_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
