"""empty message

Revision ID: 8998e5083a78
Revises: 3256149f1ca8
Create Date: 2025-11-19 16:23:00.056730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8998e5083a78'
down_revision = '3256149f1ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('gestor_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('mensagem',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('feedback_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['gestor_id'], ['id'])
        batch_op.drop_column('assunto')
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', mysql.VARCHAR(length=20), server_default=sa.text("'feedback'"), nullable=False))
        batch_op.add_column(sa.Column('assunto', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('feedback_ibfk_2'), 'usuario', ['gestor_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('mensagem',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('gestor_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
